name: Metrics
on:
  # Schedule updates (daily at midnight UTC)
  schedule: [{cron: "0 0 * * *"}]
  # Allow manual execution and trigger on push
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
            token: ${{ secrets.METRICS_TOKEN }}

            # Layout order
            config_order: base.header, base.activity+community, base.repositories, followup, languages, activity, achievements, gists, stars, traffic

            # General repository insights
            repositories_forks: yes
            plugin_languages: yes
            plugin_languages_ignored: html, css
            plugin_languages_sections: most-used
            plugin_languages_limit: 8

            # Activity & community
            plugin_stargazers: yes
            plugin_followup: yes
            plugin_gists: yes
            plugin_traffic: yes

            # Achievements
            plugin_achievements: yes
            plugin_achievements_threshold: C
            plugin_achievements_display: detailed

            # Repository insights
            plugin_repositories: yes
            plugin_repositories_featured: your-repo-name
            plugin_repositories_pinned: 4

            # Contributions & Stars
            plugin_stars: yes
            plugin_stars_limit: 5
